packages:
  - packages/*

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@breadc/color@1.0.0-beta.17'
  - '@breadc/core@1.0.0-beta.17'
  - '@breadc/death@1.0.0-beta.17'
  - '@breadc/tui@1.0.0-beta.17'
  - breadc@1.0.0-beta.17

shellEmulator: true
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
